apiVersion: v1
kind: Secret
metadata:
  name: fake-news-api-secrets
  namespace: ml-pipelines
type: Opaque
stringData:
  TG_BOT_TOKEN: "123456789:AAH_tvoje_token_zdes"
  HF_TOKEN: "shartlez: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"
  KAGGLE_TOKEN: "KGAT_500082e3989eed37e44e5e64dbc17d78"
  WANDB_API_KEY: "wandb_key_dlja_obuchenija"
  API_KEY: "super_secret_api_key_for_backend"