apiVersion: v1
kind: Secret
metadata:
  name: fake-news-api-secrets
  namespace: ml-pipelines
type: Opaque
stringData:
  TG_BOT_TOKEN: "123456789:AAH_tvoje_token_zdes"
  HUGGINGFACE_TOKEN: "hf_tvoj_token"
  WANDB_API_KEY: "wandb_key_dlja_obuchenija"
  API_KEY: "super_secret_api_key_for_backend"