apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fake-news-api-ingress
  namespace: ml-pipelines
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - nlp-api.my-company.com 
    secretName: fake-news-api-tls-secret 
  rules:
  - host: nlp-api.my-company.com 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fake-news-api-service
            port:
              number: 80