apiVersion: v1
kind: ConfigMap
metadata:
  name: fake-news-api-config
  namespace: ml-pipelines
data:
  API_PORT: "8000"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  
  MODEL_WEIGHTS_DIR: "/app/models"
  MLRUNS_DIR: "/app/logs"
  DATA_DIR: "/app/data"