# 1. Диск для весов моделей
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-models
  namespace: ml-pipelines
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 50Gi 

---
# 2. Диск для сырых датасетов классификатора
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: ml-pipelines
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
# 3. Диск для логов и SQLite базы MLflow
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: ml-pipelines
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi