# configs/model/default.yaml
defaults:
  - _self_
  - architecture: rubert_base
  # По умолчанию ставим обучение только головы, это самый частый и безопасный старт
  - finetuning: head_only 

model_name: ???

tokenizer:
  _target_: src.core.models.tokenization.HFTokenizerBuilder
  tokenizer_name: ${model.model_name}
  use_fast: True
  padding_side: "right"
  add_eos_token: False

builder:
  _target_: src.core.models.builder.HFModelBuilder
  model_name_or_path: ${model.model_name}
  cache_dir: "${paths.hf_cache_dir}"
  trust_remote_code: False
  auto_model_class: "transformers.AutoModelForSequenceClassification" 
  torch_dtype: "auto"
  num_labels: 2
  finetuning_type: ${model.finetuning.type}
  peft_config: ${model.finetuning.peft_config}
  
  # Интеграция с MLflow
  use_mlflow_registry: True
  mlflow_tracking_uri: ${logger.tracking_uri}
  mlflow_model_name: "FakeNewsDetector"
  mlflow_model_alias: "Production"