_target_: pytorch_lightning.loggers.MLFlowLogger
experiment_name: ${project_name}_${environment.name}
# По умолчанию используем локальный сервер, в проде переопределим через переменные окружения
tracking_uri: "sqlite:///${paths.log_dir}/mlflow.db" #${oc.env:MLFLOW_TRACKING_URI, "http://localhost:5000"}
run_name: ${now:%Y-%m-%d_%H-%M-%S}
log_model: True
tags:
  env: ${environment.name}